### ISSUE TITLE
Libusb not found

### ISSUE THREAD

**Issue by bobmarleyfaruk9** [jsherman212/xnuspy#13]
I have tried the followings:

- brew install libusb
- sudo port install libusb
- clone libusb from the official github repo and install
- specify the ldflags such as LDFLAGS =-L/usr/local/lib and include header statically 

unfortunately, none of them have resolved the issue. 

Any kind of help will be appreciated...

**Comment by opa334** [comment]
go into loader/Makefile and change CFLAGS and LDFLAGS to:

```
CFLAGS = -g -I/opt/homebrew/include
LDFLAGS = -L/opt/homebrew/lib -lusb-1.0
```

**Comment by bobmarleyfaruk9** [comment]
> go into loader/Makefile and change CFLAGS and LDFLAGS to:
> 
> 
> 
> ```
> 
> CFLAGS = -g -I/opt/homebrew/include
> 
> LDFLAGS = -L/opt/homebrew/lib -lusb-1.0
> 
> ```

Thank you for the answer!
Modifying the makefile to this worked for me but your solution is same/more elegant 

CC = clang
CFLAGS = -g
LDFLAGS = -L/usr/local/lib

ifeq ($(XNUSPY_SERIAL), 1)
    CFLAGS += -DXNUSPY_SERIAL
endif

TARGET = loader

SOURCES = loader.c

$(TARGET) : $(SOURCES)
    $(CC) $(CFLAGS) $(LDFLAGS) $(SOURCES) -lusb-1.0 -Wl -t -o $(TARGET)
