### ISSUE TITLE
Offsets for iPhone 8, iOS 14.8

### ISSUE THREAD

**Issue by jiska2342** [jsherman212/xnuspy#6]
Hi,

in case someone finds this useful, I tested `xnuspy` on an iPhone 8 on iOS 14.8. The offsets for the examples are as follows:

*  `open1`: `0xfffffff007c4c930`
* `getClassName`: `0xfffffff007fbd400`
* `is_io_service_open_extended`: `0xfffffff0080861a0`

Not really an issue, but you can add it to the list of offsets :)

**Comment by jsherman212** [comment]
Thank you! I'll add them in a couple of hours
