### ISSUE TITLE
How to add Build Options to make command

### ISSUE THREAD

**Issue by YiYiZheng** [jsherman212/xnuspy#9]
For example, I need to add XNUSPY_DEBUG=1 and XNUSPY_SERIAL=1. How can I write the command? Thx

**Comment by jsherman212** [comment]
You add them before `make`, so in your case, you'd do `XNUSPY_DEBUG=1 XNUSPY_SERIAL=1 make`

**Comment by YiYiZheng** [comment]
Another question:

When I followed the Usage chapter:
1. execute `/Applications/checkra1n.app/Contents/MacOS/checkra1n -p`, I enter ![image](https://user-images.githubusercontent.com/43005999/163402459-d5d6ef97-d03f-442e-abf1-f1e74c30c538.png)
2. execute `loader/loader module/xnuspy`, It is stuck in 
![image](https://user-images.githubusercontent.com/43005999/163402646-d2bab3f8-9f0f-4822-9928-912c158de001.png)

Nothing happens, and my device did not boot.

What's wrong with my operation?

Thx!

**Comment by jsherman212** [comment]
You have to start the jailbreak process with checkra1n for the phone to boot into pongoOS. Once the phone has booted into pongo, xnuspy's loader will notice and load xnuspy

**Comment by YiYiZheng** [comment]
> You have to start the jailbreak process with checkra1n for the phone to boot into pongoOS. Once the phone has booted into pongo, xnuspy's loader will notice and load xnuspy

So, do I need to start the jailbreak process every time I want to use xnuspy?

**Comment by jsherman212** [comment]
Yea, because xnuspy patches the kernel and those kernel patches are lost when you reboot, so you need to re-jailbreak to apply the kernel patches again.  xnuspy stays alive until you reboot your device. Once you reboot you have to jailbreak and load xnuspy again

**Comment by YiYiZheng** [comment]
> 

So if I disconnect device to mac, xnuspy will stay alive? Only device reboot will disable it.

**Comment by jsherman212** [comment]
Yeah
